### ISSUE TITLE
Add support for "aggregation pipeline"

### ISSUE THREAD

**Issue by jacobemcken** [gnarroway/mongo-driver-3#7]
I've been looking at the [documentation for `findAndModify`][1] and came to the conclusion that it corresponds to [`findOneAndUpdate` in the Java driver][2].

[1]: https://www.mongodb.com/docs/manual/reference/method/db.collection.findAndModify/
[2]: http://mongodb.github.io/mongo-java-driver/4.6/apidocs/mongodb-driver-sync/com/mongodb/client/MongoCollection.html#findOneAndUpdate(com.mongodb.client.ClientSession,org.bson.conversions.Bson,java.util.List,com.mongodb.client.model.FindOneAndUpdateOptions)

When I provide a map for `update` it works as expected:
```clojure
(defn find-one-and-update
  [db coll q update opts]
             ^^^^^^
```

But when I try to provide a vector (which should resemble a pipeline), then I get the exception:
```
clojure.lang.LazySeq cannot be cast to org.bson.conversions.Bson
```

I assumed that `List<? extends Bson>` means it supports both a single (a map) and a list (a vector), due to the `model.clj` namespace auto converting stuff.

Dunno if this is a bug or a feature request :grin: :shrug:

**Comment by jacobemcken** [comment]
I've tested it from the Mongo shell:
```js
db.test.insertMany( [
   {
    "_id": ObjectId("6d792d6a756963792d696441"),
    "A": [ "1", "2" ],
    "B": [ ]
  },
  {
    "_id": ObjectId("6d792d6a756963792d696442"),
    "A": [ "7", "8" ],
    "B": [ ]
  }
]);

db.test.findAndModify({
    query: {},
    update: [ { $set: {"B": "$A" }},
              { $set: {"A": []}} ],
    new: true
});
```

Using the driver I would have expected something like:
```clojure
(find-one-and-update db "test"
                     {}
                     [{$set {:B "$A"}}
                      {$set {:A []}}]
                     {:return-new true}))
```

**Comment by jacobemcken** [comment]
The following patch seems to make `find-one-and-update` support pipelines:
```patch
   ([^MongoDatabase db coll q update opts]
    (let [{:keys [keywordize? ^ClientSession session] :or {keywordize? true}} opts
          ^ClientSession session (or session *session*)
-         opts'                  (->FindOneAndUpdateOptions opts)]
+         opts'                  (->FindOneAndUpdateOptions opts)
+         bson (if (instance? List update) ^List (map document update) (document update))]
      (-> (if session
-           (.findOneAndUpdate (collection db coll opts) session (document q) (document update) opts')
-           (.findOneAndUpdate (collection db coll opts) (document q) (document update) opts'))
+           (.findOneAndUpdate (collection db coll opts) session (document q) bson opts')
+           (.findOneAndUpdate (collection db coll opts) (document q) bson opts'))
          (from-document keywordize?)))))
```

but it also introduces some reflection warnings:
```clojure
; Reflection warning, mongo_driver_3/collection.clj:251:12 - call to method findOneAndUpdate on com.mongodb.client.MongoCollection can't be resolved (argument types: com.mongodb.client.ClientSession, org.bson.Document, unknown, com.mongodb.client.model.FindOneAndUpdateOptions).
; Reflection warning, mongo_driver_3/collection.clj:252:12 - call to method findOneAndUpdate on com.mongodb.client.MongoCollection can't be resolved (argument types: org.bson.Document, unknown, com.mongodb.client.model.FindOneAndUpdateOptions).
```
So I guess not really PR material.

**Comment by gnarroway** [comment]
Thanks for raising this (and looking into it). Let me check it out shortly.

**Comment by jacobemcken** [comment]
The solution might be a bit verbose, but this was the only way I could avoid the reflection warnings.

Let me know if you have ideas for a different approach.

**Comment by jacobemcken** [comment]
Btw. it is only possible to use pipelines in `findAndUpdate` from Mongo version 4.2 and forward.
